version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3032:3443
    command: npm run dev
volumes:
  dependencies: