version: '3'
services:
  app:
    build: .
    container_name: receiver-api
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3032:3443
    command: npm start
